# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import chat_service_pb2 as chat__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/chat.ChatService/StreamChat',
                request_serializer=chat__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.InitializeDocSource = channel.unary_unary(
                '/chat.ChatService/InitializeDocSource',
                request_serializer=chat__service__pb2.InitSourceRequest.SerializeToString,
                response_deserializer=chat__service__pb2.InitSourceResponse.FromString,
                _registered_method=True)
        self.ProcessDocumentation = channel.unary_unary(
                '/chat.ChatService/ProcessDocumentation',
                request_serializer=chat__service__pb2.ProcessDocRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ProcessDocResponse.FromString,
                _registered_method=True)
        self.GetAvailableModels = channel.unary_unary(
                '/chat.ChatService/GetAvailableModels',
                request_serializer=chat__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ModelsResponse.FromString,
                _registered_method=True)
        self.GetAvailableSources = channel.unary_unary(
                '/chat.ChatService/GetAvailableSources',
                request_serializer=chat__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=chat__service__pb2.SourcesResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeDocSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDocumentation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=chat__service__pb2.ChatRequest.FromString,
                    response_serializer=chat__service__pb2.ChatResponse.SerializeToString,
            ),
            'InitializeDocSource': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeDocSource,
                    request_deserializer=chat__service__pb2.InitSourceRequest.FromString,
                    response_serializer=chat__service__pb2.InitSourceResponse.SerializeToString,
            ),
            'ProcessDocumentation': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocumentation,
                    request_deserializer=chat__service__pb2.ProcessDocRequest.FromString,
                    response_serializer=chat__service__pb2.ProcessDocResponse.SerializeToString,
            ),
            'GetAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableModels,
                    request_deserializer=chat__service__pb2.EmptyRequest.FromString,
                    response_serializer=chat__service__pb2.ModelsResponse.SerializeToString,
            ),
            'GetAvailableSources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSources,
                    request_deserializer=chat__service__pb2.EmptyRequest.FromString,
                    response_serializer=chat__service__pb2.SourcesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.ChatService/StreamChat',
            chat__service__pb2.ChatRequest.SerializeToString,
            chat__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeDocSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/InitializeDocSource',
            chat__service__pb2.InitSourceRequest.SerializeToString,
            chat__service__pb2.InitSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDocumentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/ProcessDocumentation',
            chat__service__pb2.ProcessDocRequest.SerializeToString,
            chat__service__pb2.ProcessDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetAvailableModels',
            chat__service__pb2.EmptyRequest.SerializeToString,
            chat__service__pb2.ModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetAvailableSources',
            chat__service__pb2.EmptyRequest.SerializeToString,
            chat__service__pb2.SourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
